/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jingdong_dawnslab_vulscanner_SecondFragment */

#ifndef _Included_com_jingdong_dawnslab_1vulscanner_SecondFragment
#define _Included_com_jingdong_dawnslab_1vulscanner_SecondFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jingdong_dawnslab_vulscanner_SecondFragment
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_jingdong_dawnslab_1vulscanner_SecondFragment_stringFromJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
